// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoLAWBD.Data;

#nullable disable

namespace ProjetoLAWBD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111114431_Reset")]
    partial class Reset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Administrador", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<string>("IdAdministradorCriador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_administrador_criador");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("IdAdministradorCriador");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnuncio"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_publicacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_veiculo");

                    b.Property<string>("IdVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_vendedor");

                    b.Property<string>("LocalizacaoCidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("localizacao_cidade");

                    b.Property<decimal>("Preco")
                        .HasColumnType("money")
                        .HasColumnName("preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.HasKey("IdAnuncio");

                    b.HasIndex("IdVeiculo");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Anuncio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Anuncio_Estado", "estado IN ('Ativo', 'Reservado', 'Pausado', 'Vendido', 'Arquivado')");

                            t.HasCheckConstraint("CK_Anuncio_Preco", "preco > 0");
                        });
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Bloqueio", b =>
                {
                    b.Property<int>("IdBloqueio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bloqueio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBloqueio"));

                    b.Property<DateTime>("DataBloqueio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_bloqueio");

                    b.Property<string>("IdAdministrador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_administrador");

                    b.Property<string>("IdUtilizadorAlvo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador_alvo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo");

                    b.HasKey("IdBloqueio");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdUtilizadorAlvo");

                    b.ToTable("Bloqueio", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Caixa", b =>
                {
                    b.Property<int>("IdCaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_caixa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaixa"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdCaixa");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Caixa", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Combustivel", b =>
                {
                    b.Property<int>("IdCombustivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_combustivel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombustivel"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdCombustivel");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Combustivel", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_compra");

                    b.Property<string>("EstadoPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_pagamento");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_comprador");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("money")
                        .HasColumnName("valor_total");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Compra", null, t =>
                        {
                            t.HasCheckConstraint("CK_Compra_Estado", "estado_pagamento IN ('Pago', 'Pendente', 'Cancelado')");
                        });
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Comprador", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Comprador", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.ConfNotificacoes", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<bool>("AlteracoesReservasVisitas")
                        .HasColumnType("bit")
                        .HasColumnName("alteracoes_reservas_visitas");

                    b.Property<bool>("AnunciosMarcasFavoritas")
                        .HasColumnType("bit")
                        .HasColumnName("anuncios_marcas_favoritas");

                    b.HasKey("IdUtilizador");

                    b.ToTable("ConfNotificacoes", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contacto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"));

                    b.Property<string>("IdUtilizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<string>("TipoContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_contacto");

                    b.Property<string>("ValorContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contacto");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("Contacto", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Cor", b =>
                {
                    b.Property<int>("IdCor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCor"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdCor");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Cor", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.FiltroGuardado", b =>
                {
                    b.Property<int>("IdFiltro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_filtro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiltro"));

                    b.Property<int?>("AnoMaximo")
                        .HasColumnType("int")
                        .HasColumnName("ano_maximo");

                    b.Property<int?>("AnoMinimo")
                        .HasColumnType("int")
                        .HasColumnName("ano_minimo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<int?>("IdCaixa")
                        .HasColumnType("int")
                        .HasColumnName("id_caixa");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("id_combustivel");

                    b.Property<int?>("IdCor")
                        .HasColumnType("int")
                        .HasColumnName("id_cor");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int?>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("id_modelo");

                    b.Property<string>("IdUtilizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<int?>("KmMaximo")
                        .HasColumnType("int")
                        .HasColumnName("km_maximo");

                    b.Property<string>("NomeFilto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_filtro");

                    b.Property<decimal?>("PrecoMaximo")
                        .HasColumnType("money")
                        .HasColumnName("preco_maximo");

                    b.Property<decimal?>("PrecoMinimo")
                        .HasColumnType("money")
                        .HasColumnName("preco_minimo");

                    b.HasKey("IdFiltro");

                    b.HasIndex("IdCaixa");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCombustivel");

                    b.HasIndex("IdCor");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("FiltroGuardado", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.HistoricoDeAcoes", b =>
                {
                    b.Property<int>("IdAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_acao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcao"));

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_acao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("EntidadeAlvo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entidade_alvo");

                    b.Property<string>("IdAdministradorAutor")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_administrador_autor");

                    b.Property<int?>("IdEntidadeAlvo")
                        .HasColumnType("int")
                        .HasColumnName("id_entidade_alvo");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_acao");

                    b.HasKey("IdAcao");

                    b.HasIndex("IdAdministradorAutor");

                    b.ToTable("HistoricoDeAcoes", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_imagem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<string>("CaminhoFicheiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("caminho_ficheiro");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_veiculo");

                    b.Property<bool>("IsCapa")
                        .HasColumnType("bit")
                        .HasColumnName("is_capa");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int")
                        .HasColumnName("ordem_exibicao");

                    b.HasKey("IdImagem");

                    b.HasIndex("CaminhoFicheiro")
                        .IsUnique();

                    b.HasIndex("IdVeiculo");

                    b.ToTable("Imagem", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nome");

                    b.HasKey("IdMarca");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.MarcaFavoritaComprador", b =>
                {
                    b.Property<string>("IdComprador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_comprador");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.HasKey("IdComprador", "IdMarca");

                    b.HasIndex("IdMarca");

                    b.ToTable("MarcaFavoritaComprador", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("IdModelo");

                    b.HasIndex("IdMarca");

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Morada", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("distrito");

                    b.Property<string>("RuaENumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rua_e_numero");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Morada", null, t =>
                        {
                            t.HasCheckConstraint("CK_Morada_CodigoPostal", "codigo_postal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_pedido");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_reserva");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_comprador");

                    b.Property<DateTime>("PrazoExpiracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("prazo_expiracao");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Reserva", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_Estado", "estado_reserva IN ('Pendente', 'Aprovada', 'Rejeitada', 'Expirada', 'Cancelada', 'Concluida')");
                        });
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_veiculo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculo"));

                    b.Property<int?>("CilindradaCC")
                        .HasColumnType("int")
                        .HasColumnName("cilindrada_cc");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_matricula");

                    b.Property<int>("IdCaixa")
                        .HasColumnType("int")
                        .HasColumnName("id_caixa");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("id_combustivel");

                    b.Property<int>("IdCor")
                        .HasColumnType("int")
                        .HasColumnName("id_cor");

                    b.Property<int>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("id_modelo");

                    b.Property<string>("IdVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_vendedor");

                    b.Property<int>("KmTotal")
                        .HasColumnType("int")
                        .HasColumnName("km_total");

                    b.Property<int>("NumLugares")
                        .HasColumnType("int")
                        .HasColumnName("num_lugares");

                    b.Property<int>("NumPortas")
                        .HasColumnType("int")
                        .HasColumnName("num_portas");

                    b.Property<int>("PotenciaCV")
                        .HasColumnType("int")
                        .HasColumnName("potencia_cv");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("IdCaixa");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCombustivel");

                    b.HasIndex("IdCor");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Vendedor", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_utilizador");

                    b.Property<string>("CPFaturacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("morada_faturacao_codigo_postal");

                    b.Property<string>("CidadeFaturacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("morada_faturacao_cidade");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_validacao");

                    b.Property<string>("EstadoValidacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_validacao");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iban");

                    b.Property<string>("IdAdministradorValidador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_administrador_validador");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasColumnName("nif");

                    b.Property<string>("NomeFaturacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_faturacao");

                    b.Property<string>("RuaFaturacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("morada_faturacao_rua");

                    b.Property<string>("TipoVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_vendedor");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("IdAdministradorValidador");

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.ToTable("Vendedor", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vendedor_CodigoPostal", "morada_faturacao_codigo_postal IS NULL OR morada_faturacao_codigo_postal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Vendedor_Estado", "estado_validacao IN ('Pendente', 'Aprovado', 'Rejeitado')");

                            t.HasCheckConstraint("CK_Vendedor_IBAN", "iban IS NULL OR iban LIKE 'PT50[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Vendedor_NIF", "nif LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Vendedor_Tipo", "tipo_vendedor IN ('Particular', 'Empresa')");
                        });
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Visita", b =>
                {
                    b.Property<int>("IdVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_visita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisita"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_pedido");

                    b.Property<DateTime>("DataVisita")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_visita");

                    b.Property<string>("EstadoVisita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_visita");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_comprador");

                    b.HasKey("IdVisita");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Visita", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visita_Estado", "estado_visita IN ('Pendente', 'Aprovada', 'Rejeitada', 'Expirada', 'Cancelada', 'Concluida')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Administrador", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Administrador", "AdminCriador")
                        .WithMany()
                        .HasForeignKey("IdAdministradorCriador")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProjetoLAWBD.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminCriador");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Anuncio", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Veiculo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Bloqueio", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.User", "UtilizadorAlvo")
                        .WithMany()
                        .HasForeignKey("IdUtilizadorAlvo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("UtilizadorAlvo");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Compra", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Comprador", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.ConfNotificacoes", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Contacto", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", "User")
                        .WithMany("Contactos")
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.FiltroGuardado", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Caixa", "Caixa")
                        .WithMany()
                        .HasForeignKey("IdCaixa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.Combustivel", "Combustivel")
                        .WithMany()
                        .HasForeignKey("IdCombustivel")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("IdCor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLAWBD.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("Categoria");

                    b.Navigation("Combustivel");

                    b.Navigation("Cor");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.HistoricoDeAcoes", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Administrador", "AdministradorAutor")
                        .WithMany()
                        .HasForeignKey("IdAdministradorAutor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdministradorAutor");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Imagem", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.MarcaFavoritaComprador", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Modelo", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Morada", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.User", "user")
                        .WithOne("Morada")
                        .HasForeignKey("ProjetoLAWBD.Models.Morada", "IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Reserva", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Veiculo", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Caixa", "Caixa")
                        .WithMany()
                        .HasForeignKey("IdCaixa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Combustivel", "Combustivel")
                        .WithMany()
                        .HasForeignKey("IdCombustivel")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("IdCor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("Categoria");

                    b.Navigation("Combustivel");

                    b.Navigation("Cor");

                    b.Navigation("Modelo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Vendedor", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Administrador", "AdministradorValidador")
                        .WithMany()
                        .HasForeignKey("IdAdministradorValidador")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProjetoLAWBD.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministradorValidador");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.Visita", b =>
                {
                    b.HasOne("ProjetoLAWBD.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjetoLAWBD.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("ProjetoLAWBD.Models.User", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Morada");
                });
#pragma warning restore 612, 618
        }
    }
}
